name: Github Pages Deploy

on:
  push:
    branches:
      - "dev-build"

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.17]
    
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Install and build
        run: npm install && npm run build --prod
      
      - name: Build
        run: npm run build:prod

       - name: Deploy
         if: success()
         uses: peaceiris/actions-gh-pages@v3
         with:
           publish_dir: dist/angular-ci-cd-example
           enable_jekyll: true